## add secret to SSO
apiVersion: v1
kind: Secret
metadata:
  name: github-client-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  dex.github.clientSecret: QXBwbGljYXRpb24gcmVjb25jaWxpYXRpb24gdGltZW91dCBpcyB0aGUgbWF4IGFtb3VudCBvZiB0aW1lIHJlcXVpcmVkIHRvIGRpc2NvdmVyIGlmIGEgbmV3IG1hbmlmZXN0cyB2ZXJzaW9uIGdvdA== # gen clientSecret and encode clientSecret
