apiVersion: scylla.scylladb.com/v1alpha1
kind: NodeConfig
metadata:
  name: cluster
spec:
  localDiskSetup:
    filesystems:
    - device: /dev/nvme0n1
      type: xfs
    mounts:
    - device: /dev/nvme0n1
      mountPoint: /scylla/data
      unsupportedOptions:
      - prjquota
    # raids:
    # - name: nvmes
    #   type: RAID0
    #   RAID0:
    #     devices:
    #       modelRegex: Amazon EC2 NVMe Instance Storage
    #       nameRegex: ^/dev/nvme\d+n\d+$
  placement:
    nodeSelector:
      scylla.scylladb.com/node-type: scylla
      Project: ScyllaDB-Development
    tolerations:
    - effect: NoSchedule
      key: role
      operator: Equal
      value: scylla-clusters
