apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: scylla-raid-setup
  namespace: scylla
spec:
  selector:
    matchLabels:
      name: scylla-raid-setup
  template:
    metadata:
      labels:
        name: scylla-raid-setup
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        scylla.scylladb.com/node-type: scylla
        Project: ScyllaDB-Development
      containers:
      - name: raid-setup
        image: amazonlinux:2
        securityContext:
          privileged: true
        command: ["/bin/bash", "-c"]
        args:
        - |
          yum install -y mdadm
          if [ ! -b /dev/md0 ]; then
            mdadm --create --verbose /dev/md0 --level=0 --raid-devices=2 /dev/nvme0n1 /dev/nvme1n1
            mkfs.ext4 -F /dev/md0
            mkdir -p /scylla/data
            mount /dev/md0 /scylla/data
            echo '/dev/md0 /scylla/data ext4 defaults,nofail 0 2' >> /etc/fstab
          fi
      volumeMounts:
      - name: host-fs
        mountPath: /scylla/data
      volumes:
      - name: host-fs
        hostPath:
          path: /scylla/data
