# Allows to override Scylla Manager name showing up in recommended k8s labels
nameOverride: ""
# Allows to override names used in Scylla Manager k8s objects.
fullnameOverride: ""
# Allows to customize Scylla Manager image
image:
  repository: scylladb
  pullPolicy: IfNotPresent
  tag: 3.3.0@sha256:e8c5b62c9330f91dfca24f109b033df78113d3ffaac306edf6d3c4346e1fa0bf
# Allows to customize Scylla Manager Controller image
controllerImage:
  repository: scylladb
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
# Scylla Manager log level, allowed values are: error, warn, info, debug, trace
logLevel: info
# Resources allocated to Scylla Manager pods
resources:
  limits:
    cpu: 1
    memory: 500Mi
  requests:
    cpu: 1
    memory: 500Mi
  # requests:
  #   cpu: 10m
  #   memory: 20Mi
# Resources allocated to Scylla Manager pods
controllerResources:
  # requests:
  #   cpu: 10m
  #   memory: 20Mi
  limits:
    cpu: 500m
    memory: 200Mi
  requests:
    cpu: 500m
    memory: 200Mi

# Node selector for Scylla Manager pod
nodeSelector:
  Project: ScyllaDB-Development
# # Tolerations for Scylla Manager pod
# tolerations: []
# # Affinity for Scylla Manager pod
# affinity: {}
tolerations:
  - key: "env"
    operator: "Equal"
    value: "ScyllaDB-Development"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "env"
              operator: In
              values:
                - ScyllaDB-Development
## SecurityContext holds pod-level security attributes
securityContext: {}
# Node selector for Scylla Manager Controller pod
controllerNodeSelector:
  Project: ScyllaDB-Development
# Tolerations for Scylla Manager Controller pod
controllerTolerations: []
# Affinity for Scylla Manager Controller pod
controllerAffinity: {}
## ControllerSecurityContext holds pod-level security attributes
controllerSecurityContext: {}
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
controllerServiceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
scylla:
  developerMode: true
  scyllaImage:
    tag: 6.1.1
  agentImage:
    tag: 3.3.0@sha256:dc2684f51e961d88da5a8eac2d9f165cb7a960cbf91f67f49332e7224317c96b
  datacenter: manager-dc
  racks:
    - name: manager-rack
      members: 1
      storage:
        capacity: 100Gi
        storageClassName: scylladb-local-xfs
      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          cpu: 1
          memory: 2Gi
        # limits:
        #   cpu: 2
        #   memory: 16Gi
        # requests:
        #   cpu: 1
        #   memory: 200Mi
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - ap-southeast-1a
              # - matchExpressions:
                  - key: "env"
                    operator: In
                    values:
                      - ScyllaDB-Development
# Whether to create Prometheus ServiceMonitor
serviceMonitor:
  create: false
