FROM alpine:3.9 AS yqtool
ARG YQ_VERSION=4.25.2
WORKDIR /tmp/build
RUN apk update
RUN apk add wget
RUN wget https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq_linux_amd64.tar.gz
RUN tar -xzvf yq_linux_amd64.tar.gz
RUN ls -lah
RUN chmod +x yq_linux_amd64
RUN mv yq_linux_amd64 yqtool


FROM alpine:3.9
COPY --from=yqtool /tmp/build/ /bin/yqtool
ENTRYPOINT ["/bin/yqtool"]
